#!/bin/bash
# Generate BuildInfo.swift with current build date

BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VERSION="0.6.0"

cat > Sources/ai/BuildInfo.swift <<EOF
import Foundation

enum BuildInfo {
    static let version = "$VERSION"
    static let buildDate = "$BUILD_DATE" // Auto-generated by generate-build-info.sh
}
EOF

echo "Generated BuildInfo.swift with build date: $BUILD_DATE"
